### ISSUE TITLE
Fix Section Auto-numbering

### ISSUE THREAD

**Issue by eswan18** [eswan18/premark#10]
## Overview

Premark's automatic numbering of sections is wrong, labeling all sections as `#1`. This used to work but was broken in the version 0.1 release.

## Background

Premark will automatically add section title slides if the `title` field is specified for a section.

E.g.
```yaml
sections:
  - file: template.md
  - file: intro.md
    title: Introduction
  - file: exercises.md
    title: Exercises
```

Lead slides for the Introduction and Exercises sections will be added automatically. Ideally, each section with a specified title would be numbered as well, such that the resulting title slide markdown was something like
```markdown
class: center, middle

## #2
# Exercises
```

However, right now, Premark labels every auto-titled section as `#1`.
