### ISSUE TITLE
sections.yaml should support automatic section lead slides

### ISSUE THREAD

**Issue by eswan18** [eswan18/premark#3]
Given this possible format of `sections.yaml`:
```
sections:
  - file: template.md
  - file: intro.md
  - file: material.md
  - file: exercises.md
```
...it should be possible to extend to something like this:
```

sections:
  - file: template.md
  - file: intro.md
     section-name: Introduction
  - file: material.md
     section-name: Core Materials
  - file: exercises.md
     section-name: Exercises
     section-number: false
```
And then, when stitched together, the intro and material sections would have automatic leader slides inserted:
```markdown
class: center, middle

## #2
# Introduction

```
And the exercises section would have a similar one, but without a number:
```markdown
class: center, middle


# Exercises
```

This makes it easier to add sections to a presentation – you wouldn't have to renumber all the sections after. Plus it makes it easy to have a consistent section leader slide.
